"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-04-26 00:00:00

Greenfield migration: bootstraps the full v0.4.0 schema from
SQLAlchemy metadata. Future migrations are autogenerated against
the resulting state.
"""
from typing import Sequence, Union

from alembic import op

from app.core.database import Base
import app.models.exercise  # noqa: F401 — register tables on Base.metadata


# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    Base.metadata.create_all(bind=op.get_bind())


def downgrade() -> None:
    Base.metadata.drop_all(bind=op.get_bind())
